version: '3'

services:
  python:
    build: ./docker/python
    tty: true
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    ports:
      - "8888:8888"
    command: jupyter lab --ip=0.0.0.0 --allow-root --NotebookApp.token='' --port=8888
